### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Luffytaro22** [demesameneshoa/Leaderboard#3]
> ## Hi **@demesameneshoa** 🤝 
> ### **Your project looks amazing and all the functionality works as expected! 😎** 
> ![gif](https://media.tenor.com/jXMFX8GNgXwAAAAC/good-anime.gif)

Here are a few recommendations that you could implement so your app works even better 😮 
> * There's a little issue when the user refreshes the page, the scores don't appear on the `table`. So kindly consider improving the consume of the `API`.
> * I would suggest changing the `title` of the page since it's not accurate with the web purpose.

**Comment by demesameneshoa** [comment]
Thank you for your feedback @Luffytaro22  and @Kidd254

**Comment by demesameneshoa** [comment]
Completed the aforementioned tasks
